### ISSUE TITLE
Add basic python project setup

### ISSUE THREAD

**Issue by Benardi** [Benardi/PyZPK#3]
#### Description
Add base files and directories for Python project

#### Tasks

- [ ] Add config files (e.x. setup.py)
- [ ] Add module src code dir
- [ ] Add test dir

**Comment by imraniac** [comment]
I m working on this
