### ISSUE TITLE
Add set up for Continuous Deployment 

### ISSUE THREAD

**Issue by Benardi** [Benardi/PyZPK#9]
**Is your feature request related to a problem? Please describe.**
There's no easy way right now to allow the existing Python package to deployed to PyPi

**Describe the solution you'd like**
A configuration to allow the PyZPK package to be deployed smoothly to PyPI, ideally this solution would work together with the CI.

**Describe alternatives you've considered**
Simply configuring the PyZPK project to allow a successful manual deployment to PyPI  

#### Tasks
- [ ] Perform the configuration to allow the deployment to PyPI
- [ ] Provide the steps to a successful deployment as instructions
- [ ] Make a successful deployment to Test PyPI

Depends on #3

**Comment by codeboy5** [comment]
I would like to take up this issue. I can work on it after #3 is completed.

**Comment by vineetjai** [comment]
I had done all 3 tasks.

**Comment by Benardi** [comment]
> I would like to take up this issue. I can work on it after #3 is completed.

Sorry for my delay. From now on we'll make sure that a PR will only be considered once someone has been assigned.

**Comment by vineetjai** [comment]
@Benardi I think all the tasks are done for this issue. So isn't it should be closed?

**Comment by codeboy5** [comment]
> > I would like to take up this issue. I can work on it after #3 is completed.
> 
> Sorry for my delay. From now on we'll make sure that a PR will only be considered once someone has been assigned.

Yes thanks a lot ! 
Saves a lot of time that way.
Please consider assigning issues
